const url=require('url');
const websiteUrl='https://www.google.com/search?q=github+login&sca_esv=1c3a2f112a8e4e48&rlz=1C1CHZN_enIN1167IN1167&ei=CSZ7aIf2HZOw4-EPlpPJ0Qg&oq=git&gs_lp=Egxnd3Mtd2l6LXNlcnAiA2dpdCoCCAIyFhAuGIAEGLEDGNEDGEMYgwEYxwEYigUyEBAAGIAEGLEDGEMYgwEYigUyCxAAGIAEGLEDGIMBMgsQLhiABBixAxiDATINEAAYgAQYsQMYQxiKBTIKEC4YgAQYQxiKBTIIEAAYgAQYsQMyBRAAGIAEMgUQABiABDILEAAYgAQYsQMYgwFIvC5QoQZYyBhwAngBkAEEmAGpAaABuQmqAQMwLji4AQHIAQD4AQGYAgagAswFqAIIwgIKEAAYsAMY1gQYR8ICDRAuGIAEGLADGEMYigXCAg0QABiABBiwAxhDGIoFwgITEC4YgAQYQxi0AhiKBRjqAtgBAcICExAAGIAEGEMYtAIYigUY6gLYAQHCAhEQLhiABBixAxjRAxiDARjHAcICDhAuGIAEGLEDGIMBGIoFwgINEC4YgAQYsQMYQxiKBcICCBAuGIAEGLEDwgIFEC4YgASYAw_xBdwANAFl1twQiAYBkAYKugYECAEYB5IHAzIuNKAH5GSyBwMwLjS4B7cFwgcHMi0yLjIuMsgHTw&sclient=gws-wiz-serp';
const parsedUrl=new URL(websiteUrl);
console.log("FULL URL:",parsedUrl.href);
console.log("PROTOCOL:",parsedUrl.protocol);
console.log("HOSTNAME:",parsedUrl.hostname);
console.log("PATHNAME:",parsedUrl.pathname);
console.log("SEARCH PARAMS:",parsedUrl.search);
console.log("ID PARAMS:",parsedUrl.searchParams.get('id'));
console.log("TYPE PARAM:",parsedUrl.searchParams.get('type'));
console.log("HASH:",parsedUrl.hash);
